### PR TITLE
Log everything by default

### PR DESCRIPTION
**Pull request by bewest**
See https://gist.github.com/bewest/7630980
for the history of this script.

This logs everything a user does.

### CODE REVIEW

**Comment by josegonzalez** [comment]
@progrium how do you envision that optional command working?

**Comment by josegonzalez** [comment]
Would an arbitrary string be fine? Sounds a bit weird.

**Comment by progrium** [comment]
@josegonzalez do you really have a need for this? this really seems like special case ... there's more subsystems than just sftp, and again, whatever you use to wrap the command shouldn't be included in this project. the way this works (or should work) is sort of like `exec` or `setuid`, you can pass it whatever and it'll run that... so i can image a wrapper env variable that just sits at the beginning of the forced command. if its not set, it works as usual, if its set, it runs it instead.

**Comment by jvanbaarsen** [comment]
@josegonzalez Is this still relevant?

**Comment by josegonzalez** [comment]
Probably useful for debugging.

**Comment by bewest** [comment]
The original intent was to provide a tool needed in mission critical environments to fulfill a requirement that all administrative actions be logged.  This makes it trivial to audit all administrative actions in order to help fulfill regulatory/compliance requirements. HTH.

**Comment by jvanbaarsen** [comment]
I don't think this should be a default. What do you think @josegonzalez ?

**Comment by josegonzalez** [comment]
No, probably not. Can we hide it's usage behind a flag? I'd merge once thats done.

**Comment by jvanbaarsen** [comment]
Maybe we should also add some tests?

**Comment by josegonzalez** [comment]
Yep

**Pull request closed without merging**
